[workspace]
members = [
    "programs/*"
]

[patch.crates-io]
blake3 = { git = "https://github.com/BLAKE3-team/BLAKE3", rev = "1.4.1" }

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
